package com.example.demo.dao.repository;

import com.example.demo.dao.entity.BaseNews;
import com.example.demo.dao.entity.BaseNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseNewsRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    long countByExample(BaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int deleteByExample(BaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int insert(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int insertSelective(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    List<BaseNews> selectByExample(BaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    BaseNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") BaseNews record, @Param("example") BaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int updateByExample(@Param("record") BaseNews record, @Param("example") BaseNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(BaseNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_NEWS
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    int updateByPrimaryKey(BaseNews record);

    String checkName(String title);

    String checkName2(String title, Integer id);

    int updateByKey(String id);
}