package com.example.demo.dao.repository;


import java.util.List;

import com.example.demo.dao.entity.LeaveMessage;
import com.example.demo.dao.entity.LeaveMessageExample;
import org.apache.ibatis.annotations.Param;

public interface LeaveMessageRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    long countByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int deleteByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int insert(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int insertSelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    List<LeaveMessage> selectByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    LeaveMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int updateByExample(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    int updateByPrimaryKey(LeaveMessage record);
}