package com.example.demo.dao.repository;

import com.example.demo.dao.entity.LeaveMessage;
import com.example.demo.dao.entity.LeaveMessageExample;
import com.example.demo.dto.*;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LeaveMessageRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int countByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int deleteByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int insert(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int insertSelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    List<LeaveMessage> selectByExample(LeaveMessageExample example);

    List<LeaveMsgResVO> selectByExample2(@Param("page") PageParam<LeaveMsgPageVo> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    LeaveMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int updateByExample(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEAVE_MESSAGE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    int updateByPrimaryKey(LeaveMessage record);


    List<LeaveMessage> selectByPage(@Param("page") PageParam<LeaveMsgPageVo> page);

    int selectCount(@Param("page")PageParam<LeaveMsgPageVo> page);

    List<LeaveMessage> selectAllParent();

    List<LeaveMsgResVO> selectAll();
}