#设置启动端口
server:
  port: 8318
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.133.58:3318/project?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: aliyun
    password: Wq970424++
    # 数据源详细配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#redis配置
  redis:
    password: Wq970424++
    database: 1
    port: 7424
    host: 123.57.133.58
    lettuce:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 10
        max-wait: 10000ms
#上传文件的大小设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#访问服务器图片的url
image:
  url: http://123.57.133.58:7777/images/

#设置更新时间
USER_SESSION_EXPIRE: 1800
#日志配置
logging:
  file:
    name: ./logs/demo
  level:
    com:
      example:
        demo:
          dao: debug
#服务器存放图片的位置
local:
  url: /usr/local/image
#发送邮箱验证码,发送者配置
email:
  emailSMTPHost: smtp.qq.com
  sendEmailAccount: 1274961697@qq.com
  sendEmailPrivateCode: jrifnmhmplgmhgej

userInfo:
  key: userInfos-dev
baseInfo:
  key: baseInfos-dev

