package com.example.demo.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public BaseDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("PARENT_ID =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("PARENT_ID <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("PARENT_ID >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_ID >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("PARENT_ID <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_ID <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("PARENT_ID like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("PARENT_ID not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("PARENT_ID in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("PARENT_ID not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("PARENT_ID between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_ID not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andBaseNameIsNull() {
            addCriterion("BASE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBaseNameIsNotNull() {
            addCriterion("BASE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBaseNameEqualTo(String value) {
            addCriterion("BASE_NAME =", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameNotEqualTo(String value) {
            addCriterion("BASE_NAME <>", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameGreaterThan(String value) {
            addCriterion("BASE_NAME >", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("BASE_NAME >=", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameLessThan(String value) {
            addCriterion("BASE_NAME <", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameLessThanOrEqualTo(String value) {
            addCriterion("BASE_NAME <=", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameLike(String value) {
            addCriterion("BASE_NAME like", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameNotLike(String value) {
            addCriterion("BASE_NAME not like", value, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameIn(List<String> values) {
            addCriterion("BASE_NAME in", values, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameNotIn(List<String> values) {
            addCriterion("BASE_NAME not in", values, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameBetween(String value1, String value2) {
            addCriterion("BASE_NAME between", value1, value2, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseNameNotBetween(String value1, String value2) {
            addCriterion("BASE_NAME not between", value1, value2, "baseName");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionIsNull() {
            addCriterion("BASE_INTRODUCTION is null");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionIsNotNull() {
            addCriterion("BASE_INTRODUCTION is not null");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionEqualTo(String value) {
            addCriterion("BASE_INTRODUCTION =", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionNotEqualTo(String value) {
            addCriterion("BASE_INTRODUCTION <>", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionGreaterThan(String value) {
            addCriterion("BASE_INTRODUCTION >", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("BASE_INTRODUCTION >=", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionLessThan(String value) {
            addCriterion("BASE_INTRODUCTION <", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionLessThanOrEqualTo(String value) {
            addCriterion("BASE_INTRODUCTION <=", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionLike(String value) {
            addCriterion("BASE_INTRODUCTION like", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionNotLike(String value) {
            addCriterion("BASE_INTRODUCTION not like", value, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionIn(List<String> values) {
            addCriterion("BASE_INTRODUCTION in", values, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionNotIn(List<String> values) {
            addCriterion("BASE_INTRODUCTION not in", values, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionBetween(String value1, String value2) {
            addCriterion("BASE_INTRODUCTION between", value1, value2, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBaseIntroductionNotBetween(String value1, String value2) {
            addCriterion("BASE_INTRODUCTION not between", value1, value2, "baseIntroduction");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlIsNull() {
            addCriterion("BASE_PRI_URL is null");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlIsNotNull() {
            addCriterion("BASE_PRI_URL is not null");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlEqualTo(String value) {
            addCriterion("BASE_PRI_URL =", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlNotEqualTo(String value) {
            addCriterion("BASE_PRI_URL <>", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlGreaterThan(String value) {
            addCriterion("BASE_PRI_URL >", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlGreaterThanOrEqualTo(String value) {
            addCriterion("BASE_PRI_URL >=", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlLessThan(String value) {
            addCriterion("BASE_PRI_URL <", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlLessThanOrEqualTo(String value) {
            addCriterion("BASE_PRI_URL <=", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlLike(String value) {
            addCriterion("BASE_PRI_URL like", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlNotLike(String value) {
            addCriterion("BASE_PRI_URL not like", value, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlIn(List<String> values) {
            addCriterion("BASE_PRI_URL in", values, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlNotIn(List<String> values) {
            addCriterion("BASE_PRI_URL not in", values, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlBetween(String value1, String value2) {
            addCriterion("BASE_PRI_URL between", value1, value2, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBasePriUrlNotBetween(String value1, String value2) {
            addCriterion("BASE_PRI_URL not between", value1, value2, "basePriUrl");
            return (Criteria) this;
        }

        public Criteria andBaseLocationIsNull() {
            addCriterion("BASE_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andBaseLocationIsNotNull() {
            addCriterion("BASE_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andBaseLocationEqualTo(String value) {
            addCriterion("BASE_LOCATION =", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationNotEqualTo(String value) {
            addCriterion("BASE_LOCATION <>", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationGreaterThan(String value) {
            addCriterion("BASE_LOCATION >", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationGreaterThanOrEqualTo(String value) {
            addCriterion("BASE_LOCATION >=", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationLessThan(String value) {
            addCriterion("BASE_LOCATION <", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationLessThanOrEqualTo(String value) {
            addCriterion("BASE_LOCATION <=", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationLike(String value) {
            addCriterion("BASE_LOCATION like", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationNotLike(String value) {
            addCriterion("BASE_LOCATION not like", value, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationIn(List<String> values) {
            addCriterion("BASE_LOCATION in", values, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationNotIn(List<String> values) {
            addCriterion("BASE_LOCATION not in", values, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationBetween(String value1, String value2) {
            addCriterion("BASE_LOCATION between", value1, value2, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andBaseLocationNotBetween(String value1, String value2) {
            addCriterion("BASE_LOCATION not between", value1, value2, "baseLocation");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNull() {
            addCriterion("TEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNotNull() {
            addCriterion("TEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTelNoEqualTo(String value) {
            addCriterion("TEL_NO =", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotEqualTo(String value) {
            addCriterion("TEL_NO <>", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThan(String value) {
            addCriterion("TEL_NO >", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_NO >=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThan(String value) {
            addCriterion("TEL_NO <", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThanOrEqualTo(String value) {
            addCriterion("TEL_NO <=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLike(String value) {
            addCriterion("TEL_NO like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotLike(String value) {
            addCriterion("TEL_NO not like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoIn(List<String> values) {
            addCriterion("TEL_NO in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotIn(List<String> values) {
            addCriterion("TEL_NO not in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoBetween(String value1, String value2) {
            addCriterion("TEL_NO between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotBetween(String value1, String value2) {
            addCriterion("TEL_NO not between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("ZIP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("ZIP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("ZIP_CODE =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("ZIP_CODE <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("ZIP_CODE >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("ZIP_CODE <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("ZIP_CODE like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("ZIP_CODE not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("ZIP_CODE in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("ZIP_CODE not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("ZIP_CODE between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("ZIP_CODE not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeIsNull() {
            addCriterion("FIX_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFixCodeIsNotNull() {
            addCriterion("FIX_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFixCodeEqualTo(String value) {
            addCriterion("FIX_CODE =", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeNotEqualTo(String value) {
            addCriterion("FIX_CODE <>", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeGreaterThan(String value) {
            addCriterion("FIX_CODE >", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FIX_CODE >=", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeLessThan(String value) {
            addCriterion("FIX_CODE <", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeLessThanOrEqualTo(String value) {
            addCriterion("FIX_CODE <=", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeLike(String value) {
            addCriterion("FIX_CODE like", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeNotLike(String value) {
            addCriterion("FIX_CODE not like", value, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeIn(List<String> values) {
            addCriterion("FIX_CODE in", values, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeNotIn(List<String> values) {
            addCriterion("FIX_CODE not in", values, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeBetween(String value1, String value2) {
            addCriterion("FIX_CODE between", value1, value2, "fixCode");
            return (Criteria) this;
        }

        public Criteria andFixCodeNotBetween(String value1, String value2) {
            addCriterion("FIX_CODE not between", value1, value2, "fixCode");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNull() {
            addCriterion("WEBSITE is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNotNull() {
            addCriterion("WEBSITE is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteEqualTo(String value) {
            addCriterion("WEBSITE =", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotEqualTo(String value) {
            addCriterion("WEBSITE <>", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThan(String value) {
            addCriterion("WEBSITE >", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("WEBSITE >=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThan(String value) {
            addCriterion("WEBSITE <", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThanOrEqualTo(String value) {
            addCriterion("WEBSITE <=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLike(String value) {
            addCriterion("WEBSITE like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotLike(String value) {
            addCriterion("WEBSITE not like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteIn(List<String> values) {
            addCriterion("WEBSITE in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotIn(List<String> values) {
            addCriterion("WEBSITE not in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteBetween(String value1, String value2) {
            addCriterion("WEBSITE between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotBetween(String value1, String value2) {
            addCriterion("WEBSITE not between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNull() {
            addCriterion("OPEN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNotNull() {
            addCriterion("OPEN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeEqualTo(String value) {
            addCriterion("OPEN_TIME =", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotEqualTo(String value) {
            addCriterion("OPEN_TIME <>", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThan(String value) {
            addCriterion("OPEN_TIME >", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPEN_TIME >=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThan(String value) {
            addCriterion("OPEN_TIME <", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThanOrEqualTo(String value) {
            addCriterion("OPEN_TIME <=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLike(String value) {
            addCriterion("OPEN_TIME like", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotLike(String value) {
            addCriterion("OPEN_TIME not like", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIn(List<String> values) {
            addCriterion("OPEN_TIME in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotIn(List<String> values) {
            addCriterion("OPEN_TIME not in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeBetween(String value1, String value2) {
            addCriterion("OPEN_TIME between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotBetween(String value1, String value2) {
            addCriterion("OPEN_TIME not between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationIsNull() {
            addCriterion("PUBLIC_TRANSPORTATION is null");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationIsNotNull() {
            addCriterion("PUBLIC_TRANSPORTATION is not null");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationEqualTo(String value) {
            addCriterion("PUBLIC_TRANSPORTATION =", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationNotEqualTo(String value) {
            addCriterion("PUBLIC_TRANSPORTATION <>", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationGreaterThan(String value) {
            addCriterion("PUBLIC_TRANSPORTATION >", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLIC_TRANSPORTATION >=", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationLessThan(String value) {
            addCriterion("PUBLIC_TRANSPORTATION <", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationLessThanOrEqualTo(String value) {
            addCriterion("PUBLIC_TRANSPORTATION <=", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationLike(String value) {
            addCriterion("PUBLIC_TRANSPORTATION like", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationNotLike(String value) {
            addCriterion("PUBLIC_TRANSPORTATION not like", value, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationIn(List<String> values) {
            addCriterion("PUBLIC_TRANSPORTATION in", values, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationNotIn(List<String> values) {
            addCriterion("PUBLIC_TRANSPORTATION not in", values, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationBetween(String value1, String value2) {
            addCriterion("PUBLIC_TRANSPORTATION between", value1, value2, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andPublicTransportationNotBetween(String value1, String value2) {
            addCriterion("PUBLIC_TRANSPORTATION not between", value1, value2, "publicTransportation");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1IsNull() {
            addCriterion("OTHER_INFO1 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1IsNotNull() {
            addCriterion("OTHER_INFO1 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1EqualTo(String value) {
            addCriterion("OTHER_INFO1 =", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotEqualTo(String value) {
            addCriterion("OTHER_INFO1 <>", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1GreaterThan(String value) {
            addCriterion("OTHER_INFO1 >", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO1 >=", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1LessThan(String value) {
            addCriterion("OTHER_INFO1 <", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO1 <=", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1Like(String value) {
            addCriterion("OTHER_INFO1 like", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotLike(String value) {
            addCriterion("OTHER_INFO1 not like", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1In(List<String> values) {
            addCriterion("OTHER_INFO1 in", values, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotIn(List<String> values) {
            addCriterion("OTHER_INFO1 not in", values, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1Between(String value1, String value2) {
            addCriterion("OTHER_INFO1 between", value1, value2, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO1 not between", value1, value2, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2IsNull() {
            addCriterion("OTHER_INFO2 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2IsNotNull() {
            addCriterion("OTHER_INFO2 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2EqualTo(String value) {
            addCriterion("OTHER_INFO2 =", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotEqualTo(String value) {
            addCriterion("OTHER_INFO2 <>", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2GreaterThan(String value) {
            addCriterion("OTHER_INFO2 >", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO2 >=", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2LessThan(String value) {
            addCriterion("OTHER_INFO2 <", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO2 <=", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2Like(String value) {
            addCriterion("OTHER_INFO2 like", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotLike(String value) {
            addCriterion("OTHER_INFO2 not like", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2In(List<String> values) {
            addCriterion("OTHER_INFO2 in", values, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotIn(List<String> values) {
            addCriterion("OTHER_INFO2 not in", values, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2Between(String value1, String value2) {
            addCriterion("OTHER_INFO2 between", value1, value2, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO2 not between", value1, value2, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3IsNull() {
            addCriterion("OTHER_INFO3 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3IsNotNull() {
            addCriterion("OTHER_INFO3 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3EqualTo(String value) {
            addCriterion("OTHER_INFO3 =", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotEqualTo(String value) {
            addCriterion("OTHER_INFO3 <>", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3GreaterThan(String value) {
            addCriterion("OTHER_INFO3 >", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO3 >=", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3LessThan(String value) {
            addCriterion("OTHER_INFO3 <", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO3 <=", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3Like(String value) {
            addCriterion("OTHER_INFO3 like", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotLike(String value) {
            addCriterion("OTHER_INFO3 not like", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3In(List<String> values) {
            addCriterion("OTHER_INFO3 in", values, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotIn(List<String> values) {
            addCriterion("OTHER_INFO3 not in", values, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3Between(String value1, String value2) {
            addCriterion("OTHER_INFO3 between", value1, value2, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO3 not between", value1, value2, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNull() {
            addCriterion("CREATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNotNull() {
            addCriterion("CREATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUidEqualTo(String value) {
            addCriterion("CREATE_UID =", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotEqualTo(String value) {
            addCriterion("CREATE_UID <>", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThan(String value) {
            addCriterion("CREATE_UID >", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_UID >=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThan(String value) {
            addCriterion("CREATE_UID <", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThanOrEqualTo(String value) {
            addCriterion("CREATE_UID <=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLike(String value) {
            addCriterion("CREATE_UID like", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotLike(String value) {
            addCriterion("CREATE_UID not like", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidIn(List<String> values) {
            addCriterion("CREATE_UID in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotIn(List<String> values) {
            addCriterion("CREATE_UID not in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidBetween(String value1, String value2) {
            addCriterion("CREATE_UID between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotBetween(String value1, String value2) {
            addCriterion("CREATE_UID not between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_DETAIL
     *
     * @mbg.generated Sat Feb 22 17:11:46 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}