package com.example.demo.dao.entity;

import java.util.Date;

public class BaseNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.PARENT_ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.TITLE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.CONTENT
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.CREATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.CREATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private String createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.UPDATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.UPDATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private String updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_NEWS.DEL_FLAG
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.ID
     *
     * @return the value of BASE_NEWS.ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.ID
     *
     * @param id the value for BASE_NEWS.ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.PARENT_ID
     *
     * @return the value of BASE_NEWS.PARENT_ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.PARENT_ID
     *
     * @param parentId the value for BASE_NEWS.PARENT_ID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.TITLE
     *
     * @return the value of BASE_NEWS.TITLE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.TITLE
     *
     * @param title the value for BASE_NEWS.TITLE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.CONTENT
     *
     * @return the value of BASE_NEWS.CONTENT
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.CONTENT
     *
     * @param content the value for BASE_NEWS.CONTENT
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.CREATE_DATE
     *
     * @return the value of BASE_NEWS.CREATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.CREATE_DATE
     *
     * @param createDate the value for BASE_NEWS.CREATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.CREATE_UID
     *
     * @return the value of BASE_NEWS.CREATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.CREATE_UID
     *
     * @param createUid the value for BASE_NEWS.CREATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.UPDATE_DATE
     *
     * @return the value of BASE_NEWS.UPDATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.UPDATE_DATE
     *
     * @param updateDate the value for BASE_NEWS.UPDATE_DATE
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.UPDATE_UID
     *
     * @return the value of BASE_NEWS.UPDATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public String getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.UPDATE_UID
     *
     * @param updateUid the value for BASE_NEWS.UPDATE_UID
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setUpdateUid(String updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_NEWS.DEL_FLAG
     *
     * @return the value of BASE_NEWS.DEL_FLAG
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_NEWS.DEL_FLAG
     *
     * @param delFlag the value for BASE_NEWS.DEL_FLAG
     *
     * @mbg.generated Thu Mar 26 16:32:47 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}