package com.example.demo.dao.entity;

import java.util.Date;

public class LeaveMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.ID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.USR_NO
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private String usrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private String createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private String updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.ID
     *
     * @return the value of LEAVE_MESSAGE.ID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.ID
     *
     * @param id the value for LEAVE_MESSAGE.ID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.USR_NO
     *
     * @return the value of LEAVE_MESSAGE.USR_NO
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public String getUsrNo() {
        return usrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.USR_NO
     *
     * @param usrNo the value for LEAVE_MESSAGE.USR_NO
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setUsrNo(String usrNo) {
        this.usrNo = usrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @return the value of LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @param msgContent the value for LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @return the value of LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @param createDate the value for LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @return the value of LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @param createUid the value for LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @return the value of LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @param updateDate the value for LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @return the value of LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public String getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @param updateUid the value for LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setUpdateUid(String updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @return the value of LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @param delFlag the value for LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Wed Mar 25 22:55:23 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}