package com.example.demo.dao.entity;

import java.util.Date;

public class LeaveMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.CITY_CODE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.PARENT_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.WORD_AUTHOR_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String wordAuthorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.WORD_MASTER_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String wordMasterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.MSG_LEVEL
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Integer msgLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private String updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    private Integer delFlag;

    private String areaCode;

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.ID
     *
     * @return the value of LEAVE_MESSAGE.ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.ID
     *
     * @param id the value for LEAVE_MESSAGE.ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.CITY_CODE
     *
     * @return the value of LEAVE_MESSAGE.CITY_CODE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.CITY_CODE
     *
     * @param cityCode the value for LEAVE_MESSAGE.CITY_CODE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.PARENT_ID
     *
     * @return the value of LEAVE_MESSAGE.PARENT_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.PARENT_ID
     *
     * @param parentId the value for LEAVE_MESSAGE.PARENT_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.WORD_AUTHOR_ID
     *
     * @return the value of LEAVE_MESSAGE.WORD_AUTHOR_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getWordAuthorId() {
        return wordAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.WORD_AUTHOR_ID
     *
     * @param wordAuthorId the value for LEAVE_MESSAGE.WORD_AUTHOR_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setWordAuthorId(String wordAuthorId) {
        this.wordAuthorId = wordAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.WORD_MASTER_ID
     *
     * @return the value of LEAVE_MESSAGE.WORD_MASTER_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getWordMasterId() {
        return wordMasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.WORD_MASTER_ID
     *
     * @param wordMasterId the value for LEAVE_MESSAGE.WORD_MASTER_ID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setWordMasterId(String wordMasterId) {
        this.wordMasterId = wordMasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @return the value of LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.MSG_CONTENT
     *
     * @param msgContent the value for LEAVE_MESSAGE.MSG_CONTENT
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.MSG_LEVEL
     *
     * @return the value of LEAVE_MESSAGE.MSG_LEVEL
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Integer getMsgLevel() {
        return msgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.MSG_LEVEL
     *
     * @param msgLevel the value for LEAVE_MESSAGE.MSG_LEVEL
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setMsgLevel(Integer msgLevel) {
        this.msgLevel = msgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @return the value of LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.CREATE_DATE
     *
     * @param createDate the value for LEAVE_MESSAGE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @return the value of LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.CREATE_UID
     *
     * @param createUid the value for LEAVE_MESSAGE.CREATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @return the value of LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.UPDATE_DATE
     *
     * @param updateDate the value for LEAVE_MESSAGE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @return the value of LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public String getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.UPDATE_UID
     *
     * @param updateUid the value for LEAVE_MESSAGE.UPDATE_UID
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setUpdateUid(String updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @return the value of LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LEAVE_MESSAGE.DEL_FLAG
     *
     * @param delFlag the value for LEAVE_MESSAGE.DEL_FLAG
     *
     * @mbg.generated Tue Apr 07 10:11:07 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}